# Generated by Django 4.1 on 2023-11-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='images/drones'),
        ),
    ]
