# Generated by Django 4.1 on 2023-11-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drone_fotografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestep', models.DateTimeField(auto_now_add=True)),
                ('fotografia', models.ImageField(null=True, upload_to='images/drones')),
                ('fotografia_boxes', models.ImageField(default='images/drones/null.jpg', upload_to='images/drones')),
                ('description', models.TextField()),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drone')),
            ],
            options={
                'verbose_name': 'Log ',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
