# Generated by Django 4.1 on 2023-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
