# Generated by Django 4.1 on 2023-11-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tarea_coordenadas_coordenadagps_tarea'),
        ('core', '0004_alter_log_description'),
    ]

    operations = [
    ]
